name: omnipose
channels:
  - conda-forge
  - apple
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12  # Updated to Python 3.12
  - absl-py
  - aiohttp
  - aiosignal
  - aom
  - astunparse
  - async-timeout
  - attrs
  - blinker
  - blosc
  - brotli
  - brotli-bin
  - brotlipy
  - brunsli
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - cached-property
  - cached_property
  - cachetools
  - cffi
  - cfitsio
  - charls
  - charset-normalizer
  - click
  - cryptography
  - dav1d
  - entrypoints
  - fastremap
  - flatbuffers
  - frozenlist
  - gast
  - giflib
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - grpc-cpp
  - grpcio
  - h5py
  - hdf5
  - icu
  - idna
  - imagecodecs
  - importlib-metadata
  - jpeg
  - jupyter_client
  - jupyter_core
  - jxrlib
  - keras
  - keras-preprocessing
  - krb5
  - lcms2
  - lerc
  - libabseil
  - libaec
  - libavif
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran5
  - liblapack
  - libllvm11
  - libnghttp2
  - libopenblas
  - libpng
  - libprotobuf
  - libsodium
  - libsqlite
  - libssh2
  - libtiff
  - libwebp-base
  - libzlib
  - libzopfli
  - llvm-openmp
  - lz4-c
  - markdown
  - markupsafe
  - multidict
  - nb_conda_kernels
  - ncurses
  - nest-asyncio
  - numba
  - oauthlib
  - openjpeg
  - openssl
  - opt_einsum
  - packaging
  - pip
  - pyasn1
  - pycparser
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyqtgraph
  - pyside6
  - pysocks
  - python
  - python-dateutil
  - python-flatbuffers
  - python_abi
  - pyu2f
  - pyzmq
  - re2
  - readline
  - requests
  - requests-oauthlib
  - rsa
  - six
  - snappy
  - sqlite
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - termcolor
  - tk
  - tornado
  - traitlets
  - typing-extensions
  - tzdata
  - werkzeug
  - wheel
  - wrapt
  - xz
  - zeromq
  - zfp
  - zipp
  - zlib
  - zlib-ng
  - zstd
  - networkit
  - pip:
    - torch==2.6.0  # Latest PyTorch with Apple Silicon support
    - torchvision==0.17.0
    - torchvf>=0.1.1  # Update as needed
    - numpy  # Not restricting numpy version as per request
    
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: '1'
  PYTORCH_MPS_MEMORY_ALLOCATOR: '1'  # Added for improved MPS performance
  PYTORCH_MPS_SYNC: '0'  # Better performance
  PYTORCH_MPS_ALLOW_RESERVED_MEMORY: '1'  # Better GPU memory management
